services:
  postgres:
    image: postgres:15-alpine
    container_name: meal-planning-db
    environment:
      POSTGRES_DB: mealplanning
      POSTGRES_USER: mealplanner
      POSTGRES_PASSWORD: mealplanner_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meal-planning-network

  backend:
    build: ./backend
    container_name: meal-planning-backend
    environment:
      DATABASE_URL: postgresql://mealplanner:mealplanner_password@postgres:5432/mealplanning
      NODE_ENV: development
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - meal-planning-network
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: meal-planning-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NODE_ENV: development
    ports:
      - "3002:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - meal-planning-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  meal-planning-network:
    driver: bridge